server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
#		driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # Database를 H2로 사용하겠다.
#		url: jdbc:p6spy.h2:h2:~/test  # H2 접속 정보
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  h2:
    console:
      enabled: true
      path: /h2-console 
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        #show_sql: true
#        format_sql: true
#        default_batch_fetch_size : 100
    generate-ddl: true
    defer-datasource-initialization: true # 스크립트 기반 DataSource에 대한 초기화를 EntityManagerFactory 빈이 생성되고 초기화될 때까지 지연된다.
  application:
    name: gallery

logging:
  level:
    root: warn
    '[kr.co.wikibook]': debug
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    #    '[org.springframework.security]': debug
    p6spy: info

decorator:
  datasource:
    p6spy:
      enable-logging: true

management:
  server:
    port: 9000